import Head from "next/head";
import React from "react";
import { useTranslation } from "react-i18next";
import ErrorBoundary from "@/components/containers/ErrorBoundary/ErrorBoundary";
import FooterPage from "@/components/shared/Footer/Footer";
import Navbar from "@/components/shared/Navbar/Navbar";
import { NextPageWithLayout } from "@/global/AppTypes.types";
import Layout from "@/layout/Layout/Layout";
import LayoutPage from "@/layout/LayoutPage/LayoutPage";
import Error from "../_error";

const TicTacToe = ({ errorCode }: NextPageWithLayout) => {
  const { t } = useTranslation();

  if (errorCode) {
    return <Error statusCode={errorCode} />;
  }

  return (
    <>
      <Head>
        <title>Tic Tac Toe - Game</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <ErrorBoundary>
        <LayoutPage
          title={t("Home.Head.title")}
          description={t("Home.Head.description")}
          keywords={t("Home.Head.keywords")}
        >
          <h1>Esto es un juego</h1>
        </LayoutPage>
      </ErrorBoundary>
    </>
  );
};

TicTacToe.getLayout = function getLayout(page: React.ReactElement) {
  return (
    <Layout>
      <Navbar />
      {page}
      <FooterPage />
    </Layout>
  );
};

export default TicTacToe;
